// auth.h -- pairing-token check (spec section 19).
//
// The token is generated by the desktop and handed to the device during BLE
// provisioning, then stored in NVS. Every endpoint except GET /api/device/info
// requires it; that one is exempt because discovery has to work before pairing
// and it exposes nothing sensitive.
//
// The comparison is constant-time. A byte-at-a-time strcmp leaks the length of
// the matching prefix through timing, and a token is exactly the kind of
// secret that is worth guessing one character at a time.

#pragma once

#include <stddef.h>
#include <stdint.h>

namespace net {

/** Length-independent, data-independent comparison. */
inline bool ConstantTimeEquals(const char* a, const char* b, uint32_t length) {
  if (a == nullptr || b == nullptr) return false;
  uint8_t difference = 0;
  for (uint32_t i = 0; i < length; ++i) {
    difference = static_cast<uint8_t>(
        difference | (static_cast<uint8_t>(a[i]) ^ static_cast<uint8_t>(b[i])));
  }
  return difference == 0;
}

/**
 * Checks an `Authorization: Bearer <token>` header against the stored token.
 *
 * Returns false when the device is unpaired: an unpaired device must not serve
 * a request just because no token was configured.
 */
inline bool CheckBearer(const char* header, const char* expected_token,
                        uint32_t expected_length) {
  if (expected_token == nullptr || expected_length == 0) return false;
  if (header == nullptr) return false;

  const char kPrefix[] = "Bearer ";
  const uint32_t prefix_length = sizeof(kPrefix) - 1;
  for (uint32_t i = 0; i < prefix_length; ++i) {
    if (header[i] != kPrefix[i]) return false;
  }
  const char* presented = header + prefix_length;

  // Length is not a secret worth protecting, but the bytes are.
  uint32_t presented_length = 0;
  while (presented[presented_length] != 0) ++presented_length;
  if (presented_length != expected_length) return false;

  return ConstantTimeEquals(presented, expected_token, expected_length);
}

}  // namespace net
